<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>adoracion-icon.ico</ApplicationIcon>
    <Company>Matias Orosco</Company>
    <PackageReadmeFile>README.md</PackageReadmeFile>
	<!-- Version settings -->
	<AssemblyVersion>0.9.9.0</AssemblyVersion>
    <AssemblyName>Adoracion</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="adoracion-icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Hymns\" />
    <Folder Include="resources\" />
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <Content Include="resources\Languages.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Compile Update="Models\MediaFile.cs" />
    <Compile Update="Models\ScreenInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp" Version="3.9.6" />
    <PackageReference Include="LibVLCSharp.WPF" Version="3.9.6" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.5" />
    <PackageReference Include="SQLite" Version="3.13.0" />
    <PackageReference Include="VideoLAN.LibVLC.Windows.GPL" Version="3.0.23" />
    <PackageReference Include="Octokit" Version="14.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Hymns\add_media_here.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Content Include="resources\default_background.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <!-- Ensure all custom theme XAML files are copied to the output directory -->
    <Content Include="Themes\Color_Themes\**\*.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="UserSettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
